version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - pip install --upgrade awscli==1.18.17 
      - aws --version
      - ls -l  
      - $(aws ecr get-login --no-include-email --region us-west-2)
      - pwd
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker images 
      - docker build -t webcontainer .
      - docker tag webcontainer:latest 434024090245.dkr.ecr.us-west-2.amazonaws.com/webcontainer:latest
      - docker images 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 434024090245.dkr.ecr.us-west-2.amazonaws.com/webcontainer:latest


